# SPDX-FileCopyrightText: 2026 Skye Soss <skye@soss.website>
#
# SPDX-License-Identifier: Apache-2.0

# The formatter multiplexer - https://github.com/numtide/treefmt

[formatter.nixfmt]
command = "nixfmt"
includes = [ "*.nix" ]
excludes = [ "patches/**" ]
